import React from 'react';
import Head from 'next/head'
import NavBar from '../components/NavBar';


const layout = ({children}) => {
  return <div>


      <Head>
        <title>Portalite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Logo-Portalite-Rogne.png" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"></link>
      </Head>
      <NavBar/>
      {children}
  </div>;
};

export default layout;
